# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/a5ultexx/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/j5nltexx/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/j5nltexx/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/samsung/j5nltexx/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/j5nltexx/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/j5nltexx/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/j5nltexx/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/j5nltexx/proprietary/lib/libaudio-ril.so:system/lib/libaudio-ril.so

